name: formly
description: form with macros
version: 1.0.0

homepage: https://github.com/Ali1Ammar/formly
repository: https://github.com/Ali1Ammar/formly

environment:
  sdk: ">=3.5.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  collection: ^1.18.0
  common_macros: ^0.1.0-7.dev
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  macro_util: ^0.1.0-13.dev
  macros: ^0.1.0-main.5
  source_gen: ^1.5.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
