name: form_kit
description: form with macros
version: 1.0.0

homepage: https://github.com/Ali1Ammar/form_kit
repository: https://github.com/Ali1Ammar/form_kit

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
